name: Test Deployment

on:
  push:
    branches: [ deployement ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test secrets
      run: |
        echo "Testing if secrets are available..."
        echo "AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}"
        echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
        echo "AWS_ACCESS_KEY_ID exists: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
        echo "AWS_SECRET_ACCESS_KEY exists: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
        
    - name: Test Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Test build
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Testing if package.json exists..."
        ls -la package.json
        echo "✅ Basic tests complete"
